# Makefile for the MSX Turbo-R FDD driver for Nextor 3.
#
# This driver can be built in two flavors:
#
#   * ROM driver (default): combined with a Nextor kernel base file to
#     produce a full Nextor ROM image, ready to be flashed to an MSX
#     ROM cartridge using an ASCII16 mapper. Built by `make` or
#     `make rom`.
#
#   * RAM driver: standalone .drv file that loads into a mapped RAM
#     segment at runtime via CALL IDRIVER or the DRVROP.COM tool.
#     Built by `make ram`. Doesn't need NEXTOR_BASE.
#
# Both flavors come out under `bin/`:
#
#   * bin/Nextor-<ver>.TurboRFDD.ROM       - ROM driver
#   * bin/turbofdd.drv                     - RAM driver
#
# Intermediate build artifacts go to `tmp/`.
#
# <ver> is read from the SDK's nextor-kernel-version.txt (the authoritative
# kernel version, generated by the Nextor kernel Makefile from its version
# constants). Any variant suffix (e.g. ".NO_UNDOC.SHIFT_INV") is taken from the
# NEXTOR_BASE filename, which is expected to follow either the repository
# convention Nextor-<ver>.base[<suffix>].dat or the Docker image convention
# kernel_base[<suffix>].dat; a non-standard filename just yields no variant
# suffix.
#
# The default slot for the Turbo-R FDC hardware is 3-2 (slot byte 8Bh
# = slot 3 + 4*subslot 2 + 128). Override at build time for the ROM
# variant by setting FDC_SLOT on the make command line (e.g. FDC_SLOT=8Bh);
# for the RAM variant the slot is configured at load time via CALL
# IDRIVER / DRVROP.COM, not at assembly time.
#
# To build inside the Nextor dev Docker image instead of with a local
# toolchain, use the docker-build.sh wrapper (see README): the image provides
# N80, mknexrom, the SDK and the kernel base files, presetting NEXTOR_BASE and
# NEXTOR_SDK so this Makefile needs no extra configuration. To build against
# every kernel base variant in a directory (one `make` per base file), plus
# both forms of the RAM driver, use build-all.sh, locally or via
# `docker-build.sh --variant all`.


### Configurable variables ###################################################

# Targets that don't need NEXTOR_BASE.
_NO_BASE_GOALS := setup clean clean-bin distclean ram

# Compute whether NEXTOR_BASE is required for this make invocation.
ifeq ($(MAKECMDGOALS),)
_NEEDS_BASE := 1
else
_NEEDS_BASE := $(if $(filter-out $(_NO_BASE_GOALS),$(MAKECMDGOALS)),1,)
endif

ifeq ($(_NEEDS_BASE),1)
ifeq ($(strip $(NEXTOR_BASE)),)
$(error NEXTOR_BASE is not set. Point it at a Nextor kernel base .dat file (or use `make ram` for the RAM-only driver, which does not need it))
endif
ifeq ($(wildcard $(NEXTOR_BASE)),)
$(error NEXTOR_BASE points at '$(NEXTOR_BASE)' which does not exist)
endif
endif

# NEXTOR_SDK: path to the Nextor SDK directory (the one containing 'asm/').
# Defaults to the bundled git submodule.
NEXTOR_SDK ?= external/Nextor/sdk

# Tool overrides. Default to invoking the executables from PATH.
N80      ?= N80
MKNEXROM ?= mknexrom

# NO_UNDOC_CPU_INSTRUCTIONS: when non-empty (e.g. =1) the driver is assembled
# with undocumented Z80 opcodes (those operating on ixh/ixl/iyh/iyl) replaced
# with documented equivalents, for compatibility with Z180-based MSX machines.
# It is inferred from the NEXTOR_BASE filename (see "Build flag inference"
# below): set when the base file's variant suffix contains NO_UNDOC, unset
# otherwise, so the ROM driver always matches the kernel it is combined with.
# An explicit value (environment or command line, even an empty one) overrides
# the inference. The RAM driver isn't combined with a kernel base, so for its
# undoc-free form (`make ram`, output turbofdd.NO_UNDOC.drv) set the flag
# explicitly - with no NEXTOR_BASE there is nothing to infer from.

# FDC_SLOT (ROM build only): override the FDC hardware slot at
# assembly time. Default 8Bh = slot 3-2 (the standard for the
# FS-A1GT/FS-A1ST). Value format: slot + 4*subslot + 128 (e.g. 8Bh
# for 3-2, 8Fh for 3-3). For the RAM build, the slot is set at load
# time instead.
FDC_SLOT ?=


### Output directories #######################################################

BIN := bin
TMP := tmp


### Filename derivation ######################################################

# The kernel version for the ROM name comes from the SDK (authoritative):
# nextor-kernel-version.txt is generated by the Nextor kernel Makefile from
# its version constants, so the name always matches the kernel the SDK targets.
_VERSION_FILE         := $(NEXTOR_SDK)/nextor-kernel-version.txt
NEXTOR_KERNEL_VERSION := $(strip $(shell cat $(_VERSION_FILE) 2>/dev/null))

ifeq ($(NEXTOR_KERNEL_VERSION),)
ifeq ($(filter $(_NO_BASE_GOALS),$(MAKECMDGOALS)),)
$(error Could not read $(_VERSION_FILE). Is the Nextor SDK submodule initialized and up to date? Run 'make setup')
endif
endif

# The variant suffix (e.g. '.NO_UNDOC.SHIFT_INV') is a property of the base
# file, so it is taken from the NEXTOR_BASE filename. Two naming conventions
# are recognized, both carrying the suffix right after a 'base' token:
#   * the repository convention      'Nextor-<ver>.base[<suffix>].dat'
#   * the Docker image convention    'kernel_base[<suffix>].dat'
# A suffix is present only when 'base' is followed by a '.', so a plain
# '...base.dat' (or any non-standard filename) yields no variant suffix.
_BASE_NAME := $(notdir $(NEXTOR_BASE))
_BASE_STEM := $(_BASE_NAME:.dat=)
ifeq ($(findstring base.,$(_BASE_STEM)),base.)
_VARIANT := .$(lastword $(subst base., ,$(_BASE_STEM)))
else
_VARIANT :=
endif

### Build flag inference #####################################################

# The undoc-free kernel bases carry NO_UNDOC in their variant suffix, so unless
# the flag was given explicitly (`origin` is 'undefined' only when it was not
# set anywhere, and a deliberate empty value counts as set), derive it from
# the suffix. A base file with a non-standard name yields no suffix, hence no
# inference: set the flag by hand in that case. This also determines the RAM
# driver's output name (turbofdd[.NO_UNDOC].drv), so it must happen before the
# output names are derived below.
ifeq ($(origin NO_UNDOC_CPU_INSTRUCTIONS),undefined)
NO_UNDOC_CPU_INSTRUCTIONS := $(if $(findstring NO_UNDOC,$(_VARIANT)),1,)
endif


### Output names #############################################################

_DRIVER_PREFIX := Nextor-$(NEXTOR_KERNEL_VERSION).TurboRFDD

ROM       := $(BIN)/$(_DRIVER_PREFIX)$(_VARIANT).ROM
_RAM_SUFFIX := $(if $(NO_UNDOC_CPU_INSTRUCTIONS),.NO_UNDOC)
RAM_DRV   := $(BIN)/turbofdd$(_RAM_SUFFIX).drv


### Assembly flags ###########################################################

N80_FLAGS := --no-string-escapes --no-show-banner --verbosity 0 \
             --build-type abs --output-file-extension bin \
             --output-file-case lower \
             --include-directory $(NEXTOR_SDK)

_DEFINES_NO_UNDOC := $(if $(NO_UNDOC_CPU_INSTRUCTIONS),--define-symbols NO_UNDOC_CPU_INSTRUCTIONS)
_DEFINES_FDC_SLOT := $(if $(FDC_SLOT),--define-symbols FDC_SLOT=$(FDC_SLOT))


### Build-flag tracking ######################################################

# NO_UNDOC and FDC_SLOT both change how the driver is assembled but appear in
# no source file, so make can't see them change between runs. Both affect the
# assembled driver binary (tmp/driver.bin) yet neither shows up in the ROM
# filename, so switching either between runs without `make clean` would
# silently reuse a stale driver binary. Record both in a stamp file that the
# driver intermediates (and the RAM driver output) depend on, forcing a
# reassembly when either flag changes.
_BUILD_ID    := undoc=$(if $(NO_UNDOC_CPU_INSTRUCTIONS),1,0) fdcslot=$(FDC_SLOT)
_BUILD_STAMP := $(TMP)/.build-id

# Rewrite the stamp only when the id actually changes, so its mtime (and hence
# the rebuild) is triggered only on a real flag change. FORCE makes the recipe
# run every build to perform the check.
$(_BUILD_STAMP): FORCE | $(TMP)
	@printf '%s\n' '$(_BUILD_ID)' | cmp -s - $@ || printf '%s\n' '$(_BUILD_ID)' > $@


### Top-level targets ########################################################

# Set explicitly: the build-flag stamp rule above is the first target in the
# file, so without this `make` with no arguments would build only the stamp.
.DEFAULT_GOAL := all

.PHONY: all rom ram clean clean-bin distclean setup FORCE
all: rom

FORCE:

rom: $(ROM)
ram: $(RAM_DRV)

# Order-only prereqs for outputs that live in the build directories.
$(BIN) $(TMP):
	@mkdir -p $@


### ROM build ################################################################

# Driver binary for the ROM build (FDC_SLOT can be overridden at assembly time).
$(TMP)/driver.bin: driver.asm $(_BUILD_STAMP) | $(TMP)
	$(N80) driver.asm $(TMP)/ $(N80_FLAGS) $(_DEFINES_NO_UNDOC) $(_DEFINES_FDC_SLOT)

# Bank-switching routine for the ASCII16 mapper.
$(TMP)/chgbnk.bin: chgbnk.asm $(_BUILD_STAMP) | $(TMP)
	$(N80) chgbnk.asm $(TMP)/ $(N80_FLAGS) $(_DEFINES_NO_UNDOC)

# The Turbo-R FDD driver assembles starting at 4100h, so a 256-byte
# zero block is prepended to the driver binary before mknexrom
# combines it with the kernel base.
$(TMP)/256.bytes: | $(TMP)
	dd if=/dev/zero of=$@ bs=1 count=256

$(ROM): $(TMP)/driver.bin $(TMP)/chgbnk.bin $(TMP)/256.bytes | $(BIN)
	cat $(TMP)/256.bytes $(TMP)/driver.bin > $(TMP)/_driver.padded.bin
	$(MKNEXROM) $(NEXTOR_BASE) $@ /d:$(TMP)/_driver.padded.bin /m:$(TMP)/chgbnk.bin
	rm -f $(TMP)/_driver.padded.bin


### RAM driver build #########################################################

# `--define-symbols RAM_DRIVER` selects the RAM build path inside
# driver.asm. The output goes directly to bin/turbofdd[.NO_UNDOC].drv.
$(RAM_DRV): driver.asm $(_BUILD_STAMP) | $(BIN)
	$(N80) driver.asm $@ $(N80_FLAGS) $(_DEFINES_NO_UNDOC) --define-symbols RAM_DRIVER


### Housekeeping #############################################################

# `make clean` keeps shippable outputs in bin/, only wipes intermediates.
clean:
	rm -rf $(TMP)

# `make clean-bin` removes the shippable outputs.
clean-bin:
	rm -rf $(BIN)

# `make distclean` removes both.
distclean: clean clean-bin


### One-time setup ###########################################################

# `make setup` initializes the Nextor SDK submodule as a blobless
# partial clone with sparse-checkout for the `sdk/` directory only, so
# that the full Nextor repository is never fetched. Run this once,
# right after cloning this repo, instead of using `git clone
# --recurse-submodules`.
setup:
	@echo "Setting up the Nextor SDK submodule (blobless + sparse-checkout for sdk/ only)..."
	git submodule init external/Nextor
	git submodule update --init --filter=blob:none external/Nextor
	git -C external/Nextor sparse-checkout init --cone
	git -C external/Nextor sparse-checkout set sdk
	git -C external/Nextor checkout
	@echo "Done. Set NEXTOR_BASE and run 'make' to build the ROM, or run 'make ram' for the RAM driver."
